"""Generate a checked absorption report for optional external backends."""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
COMPARE = ROOT / "differential" / "compare.py"
REPORT = ROOT / "differential" / "ABSORPTION_REPORT.md"


BACKEND_STAGES = {
    "trade-signal": ["normalize", "fractal", "stroke", "zhongshu"],
    "chanpy": ["normalize", "fractal", "stroke", "zhongshu"],
    "czsc-native": ["normalize", "fractal", "stroke", "zhongshu"],
    "czsc-pypi-rs": ["pipeline"],
}


def _run_json(backend: str, stage: str) -> tuple[int, dict | None, str]:
    proc = subprocess.run(
        [sys.executable, str(COMPARE), "--backend", backend, "--stage", stage, "--json"],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    if proc.stdout.strip():
        try:
            return proc.returncode, json.loads(proc.stdout), proc.stderr.strip()
        except json.JSONDecodeError:
            return proc.returncode, None, proc.stdout.strip() + proc.stderr.strip()
    return proc.returncode, None, proc.stderr.strip()


def main() -> int:
    rows = []
    failures = []
    for backend, stages in BACKEND_STAGES.items():
        for stage in stages:
            rc, data, err = _run_json(backend, stage)
            if data is None:
                rows.append((backend, stage, "SKIP-LOUD", "-", "-", "-", err or "no JSON output"))
                if rc not in (0, 2):
                    failures.append((backend, stage, err))
                continue
            status = "SKIP-LOUD" if data.get("skipped") == data["total"] else (
                "OK" if data["unknown_divergence"] == 0 else "FAIL"
            )
            rows.append((
                backend,
                stage,
                status,
                str(data["equal"]),
                str(data["known_profile_divergence"]),
                str(data["unknown_divergence"]),
                f"total={data['total']} skipped={data.get('skipped', 0)}",
            ))
            if data["unknown_divergence"] != 0:
                failures.append((backend, stage, "unknown divergence"))

    lines = [
        "# External absorption report",
        "",
        "This report is generated by `python3 differential/absorption_report.py`.",
        "It records which external implementation stages have been absorbed as",
        "differential evidence without changing `chanlun-v1`.",
        "",
        "| backend | stage | status | equal | known_profile_divergence | unknown_divergence | note |",
        "|---|---|---:|---:|---:|---:|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    lines.extend([
        "",
        "Interpretation:",
        "",
        "- `equal` means byte-identical to the frozen corpus for that stage.",
        "- `known_profile_divergence` means real external output differed or lacked a canonical witness,",
        "  and the difference stayed profile-local.",
        "- `unknown_divergence` is a failure: it means a non-profile backend drifted or an external",
        "  backend raised outside its declared profile gap.",
        "- `czsc-native` calls `czsc._native` when that GitHub-master-style package is importable;",
        "  otherwise it is SKIP-LOUD and never falls back to older PyPI Python semantics.",
        "- `czsc-pypi-rs` calls the PyPI `rs_czsc` runtime from the optional isolated venv;",
        "  its online analyzer state is recorded as profile-local unless byte-identical.",
        "- `chanpy` calls a local Vespa314/chan.py source tree through an in-memory custom DataAPI",
        "  when `CHANPY_ROOT` is set or `/tmp/chanlun-externals/chan.py` exists.",
        "- Full-pipeline field projections are tracked separately in",
        "  `differential/PIPELINE_PROJECTION_REPORT.md`.",
        "- Source-level absorption evidence is tracked in `differential/SOURCE_AUDIT_REPORT.md`.",
        "",
    ])
    REPORT.write_text("\n".join(lines), "utf-8")
    print(f"wrote {REPORT}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
