"""Audit external source anchors used by profiles.

This is not a conformance run. It records source-level facts we rely on when
absorbing external implementations: which semantic knobs exist, and why their
outputs must remain profile-local unless a runtime differential proves equality.
"""
from __future__ import annotations

import json
import os
import sys
import urllib.request
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / ".external-audit-cache"
REPORT = ROOT / "differential" / "SOURCE_AUDIT_REPORT.md"


SOURCES = {
    "chan.py/BiList.py": {
        "local": os.environ.get("CHANPY_ROOT", "/tmp/chanlun-externals/chan.py") + "/Bi/BiList.py",
        "url": "https://raw.githubusercontent.com/Vespa314/chan.py/main/Bi/BiList.py",
        "checks": [
            ("strict_span_ge_4", "return bi_span >= 4"),
            ("gap_as_kl_knob", "gap_as_kl"),
            ("virtual_bi_path", "try_add_virtual_bi"),
            ("end_peak_gate", "end_is_peak"),
        ],
    },
    "chan.py/ChanConfig.py": {
        "local": os.environ.get("CHANPY_ROOT", "/tmp/chanlun-externals/chan.py") + "/ChanConfig.py",
        "url": "https://raw.githubusercontent.com/Vespa314/chan.py/main/ChanConfig.py",
        "checks": [
            ("bi_algo_knob", "bi_algo"),
            ("seg_algo_knob", "seg_algo"),
            ("zs_algo_knob", "zs_algo"),
            ("bsp_config_knobs", "set_bsp_config"),
        ],
    },
    "czsc/README.md": {
        "local": os.environ.get("CZSC_ROOT", "/tmp/chanlun-externals/czsc") + "/README.md",
        "url": "https://raw.githubusercontent.com/waditu/czsc/master/README.md",
        "checks": [
            ("rust_python_hybrid", "Rust + Python"),
            ("native_core", "czsc._native"),
            ("signals", "220+"),
            ("bar_generator", "BarGenerator"),
        ],
    },
    "czsc/crates/czsc-core/src/lib.rs": {
        "local": os.environ.get("CZSC_ROOT", "/tmp/chanlun-externals/czsc") + "/crates/czsc-core/src/lib.rs",
        "url": "https://raw.githubusercontent.com/waditu/czsc/master/crates/czsc-core/src/lib.rs",
        "checks": [
            ("core_analyze_module", "pub mod analyze"),
            ("core_objects_module", "pub mod objects"),
            ("python_feature", "feature = \"python\""),
        ],
    },
    "czsc/pyproject.toml": {
        "local": os.environ.get("CZSC_ROOT", "/tmp/chanlun-externals/czsc") + "/pyproject.toml",
        "url": "https://raw.githubusercontent.com/waditu/czsc/master/pyproject.toml",
        "checks": [
            ("maturin_backend", 'build-backend = "maturin"'),
            ("native_module_name", 'module-name      = "czsc._native"'),
            ("native_manifest_path", 'manifest-path    = "crates/czsc-python/Cargo.toml"'),
        ],
    },
}


def _read_source(name: str, spec: dict) -> tuple[str, str]:
    local = Path(spec["local"])
    if local.exists():
        return local.read_text("utf-8", errors="replace"), str(local)

    CACHE.mkdir(exist_ok=True)
    cache_path = CACHE / (name.replace("/", "__"))
    if cache_path.exists():
        return cache_path.read_text("utf-8", errors="replace"), str(cache_path)

    try:
        with urllib.request.urlopen(spec["url"], timeout=20) as resp:
            text = resp.read().decode("utf-8", errors="replace")
    except Exception as exc:
        raise RuntimeError(f"SKIP-LOUD: cannot read {name}: {exc}") from exc
    cache_path.write_text(text, "utf-8")
    return text, spec["url"]


def main() -> int:
    rows = []
    failures = []
    for name, spec in SOURCES.items():
        try:
            text, source = _read_source(name, spec)
        except RuntimeError as exc:
            rows.append((name, "SKIP-LOUD", "-", str(exc)))
            failures.append(str(exc))
            continue
        missing = [label for label, needle in spec["checks"] if needle not in text]
        status = "OK" if not missing else "FAIL"
        note = "all anchors present" if not missing else "missing " + ",".join(missing)
        rows.append((name, status, source, note))
        if missing:
            failures.append(f"{name}: {note}")

    lines = [
        "# External source audit report",
        "",
        "Generated by `python3 differential/source_audit.py`.",
        "This is source-level evidence only; runtime equality still requires",
        "`differential/compare.py` against `chanlun-v1`.",
        "",
        "| source | status | read_from | note |",
        "|---|---:|---|---|",
    ]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    lines.extend([
        "",
        "Absorption interpretation:",
        "",
        "- `chan.py` contributes realtime/current-frame concepts and configurable BI/SEG/ZS/BSP knobs.",
        "- `czsc` contributes Rust/PyO3 performance, BarGenerator, signals/trader product surfaces.",
        "- `czsc` runtime absorption requires a built/importable `czsc._native`; PyPI 0.10.x is not a substitute for master.",
        "- Neither source audit changes canonical geometry. Runtime equality must be proven fixture-by-fixture.",
        "",
    ])
    REPORT.write_text("\n".join(lines), "utf-8")
    print(f"wrote {REPORT}")
    return 1 if failures else 0


if __name__ == "__main__":
    raise SystemExit(main())
